databases:
  - name: dynprot-db
    databaseName: dynprot_db
    user: dynprot_user
    plan: free

services:
  - type: web
    name: dynprot-frontend
    env: static
    staticPublishPath: dist
    buildCommand: pnpm install && pnpm run build
    rootDir: dynprot-app
    envVars:
      - key: VITE_API_URL
        value: https://dynprot-backend.onrender.com

  - type: web
    name: dynprot-backend
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: pnpm run start
    rootDir: dynprot-app/dynprot-backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: dynprot-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: CORS_ORIGIN
        value: https://dynprot-frontend.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 60000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 1000
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_PATH
        value: ./uploads
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o
      - key: OPENAI_VISION_MODEL
        value: gpt-4o
      - key: OPENAI_MAX_TOKENS
        value: 1000
      - key: OPENAI_TEMPERATURE
        value: 0.3
      - key: CLOUDINARY_CLOUD_NAME
        value: ducmkinst
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: AI_CONFIDENCE_THRESHOLD
        value: 0.7
      - key: AI_MAX_RETRIES
        value: 2
      - key: AI_TIMEOUT_MS
        value: 30000
